CREATE TABLE CLIENTE
(
	ID_CLIENTE INT IDENTITY (1, 1)NOT NULL PRIMARY KEY,
	NOME VARCHAR (200),
	SEXO VARCHAR (10),
	CPF_CNPJ VARCHAR (30),
	DATA_NASCIMENTO DATE,
	RG VARCHAR (10),
	TELEFONE VARCHAR (10),
	CELULAR VARCHAR (30),
	ENDERECO VARCHAR (255),
	PROFISSAO VARCHAR (150),
	DATA_CADASTRO DATE,
	ULTIMO_EVENTO DATE,
	ONDE_CONHECEU VARCHAR (100),
	DESCONTO FLOAT,
	FACEBOOK VARCHAR (100),
	INSTAGRAM VARCHAR (100),
	EMAIL VARCHAR (100)
)

CREATE TABLE PRODUTO
(
	ID_PRODUTO INT IDENTITY (1, 1)NOT NULL PRIMARY KEY,
	CODIGO INT,
	FORNECEDOR VARCHAR (100),
	NOME_PRODUTO VARCHAR (200),
	COR VARCHAR (20),
	TAMANHO VARCHAR (15),
	QTD_ESTOQUE INT,
	VALOR_COMPRA DECIMAL (10, 2),
	VALOR_UNITARIO DECIMAL (10, 2),
	VALOR_REPOSICAO DECIMAL (10, 2),
	DESCRICAO VARCHAR (255),
)

CREATE TABLE VENDA
(
	ID_PEDIDO INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	ID_CLIENTE INT NOT NULL,
	DATA_EMISSAO DATE,
	DATA_EVENTO DATE,
	ATENDENTE VARCHAR (100),
	CLIENTE VARCHAR (200),
	CPF VARCHAR (20),
	FORMA_PGTO VARCHAR (50),
	VALOR DECIMAL (10, 2),
	FRETE DECIMAL (10, 2),
	DESCONTO DECIMAL (10, 2),
	CONSTRAINT FK_VENDAS2 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
	
)

CREATE TABLE REPOSICAO_MATERIAL
(
	ID_PEDIDO INT NOT NULL,
	NOME_CLIENTE VARCHAR(200),
	NOME_PRODUTO VARCHAR (200),
	QUANTIDADE INT,
	DATA_DEVOLUCAO DATE,
	VALOR_REPOSICAO DECIMAL (10, 2),
	STATUS_PGTO_REP VARCHAR (5),
	CONSTRAINT FK_REP3 FOREIGN KEY (ID_PEDIDO) REFERENCES VENDA(ID_PEDIDO)
)

CREATE TABLE PRODUTIVIDADE
(
	ID_PEDIDO INT NOT NULL,
	USUARIO VARCHAR (50),
	CLINTE VARCHAR (200),
	DATA_ATENDIMENTO DATE,
	DATA_EVENTO DATE,
	VALOR_TOTAL DECIMAL (10,2),
	FRETE DECIMAL (10,2),
	STATUS VARCHAR (20),
	ID_PRODUTO INT NOT NULL,
	NOME_PROD VARCHAR (200),
	QUANTIDADE INT,
	CONSTRAINT FK_PD1 FOREIGN KEY (ID_PEDIDO) REFERENCES VENDA(ID_PEDIDO),
	CONSTRAINT FK_PD2 FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
	
)

CREATE TABLE CONTAS_RECEBER
(
	ID_PEDIDO INT NOT NULL,
	NOME_CLIENTE VARCHAR (255),
	FORMA_PGTO VARCHAR (20),
	VENCIMENTO DATE,
	VALOR DECIMAL (10, 2),
	STATUS VARCHAR (5),
	DECRICAO VARCHAR (100),
	CONSTRAINT FK_CR2 FOREIGN KEY (ID_PEDIDO) REFERENCES VENDA(ID_PEDIDO)
)
